version: "3.5"

services:
  dbsql:
    image: mysql
    container_name: dbsql
    hostname: dbsql
    environment:
      - MYSQL_ROOT_PASSWORD=VERYSECRET
    ports:
      - 3008:3306
    volumes:
      - ./storage/schema.sql:/docker-entrypoint-initdb.d/schema.sql:rw

  db-sql-02:
    image: mysql
    container_name: db-sql-02
    hostname: db-sql-02
    environment:
      - MYSQL_ROOT_PASSWORD=VERYSECRET

  db-sql-03:
    image: mysql
    container_name: db-sql-03
    hostname: db-sql-03
    environment:
      - MYSQL_ROOT_PASSWORD=VERYSECRET

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - 3020:5432
    environment:
      - POSTGRES_PASSWORD=VERYSECRET

  pg:
    image: postgres
    container_name: pg
    hostname: pg
    environment:
      - POSTGRES_PASSWORD=VERYSECRET

  db-maria:
    image: mariadb
    container_name: db-maria
    hostname: db-maria
    environment:
      - MARIADB_ROOT_PASSWORD=VERYSECRET

  db-maria-02:
    image: mariadb
    container_name: db-maria-02
    hostname: db-maria-02
    environment:
      - MARIADB_ROOT_PASSWORD=VERYSECRET

  db:
    image: mysql
    container_name: db
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=VERYSECRET
  web:
    build: .
    restart: on-failure
    container_name: web
    hostname: web
    ports:
      - "3000:3000"
    environment:
      - LISTEN_ADDR=:3000
      - DB_USER=apt_db_platform
      - DB_PASSWORD=1qaz!EDC
      - DB_ADDRESS=dbsql:3306
      - DB_NAME=db_platform
      - JWT_SECRET=DONOTSHOWTHISTOANYONEnew
      - CRYPTO_SECRET=BNM8uXzhdfWEgMZxFr6smtM_Ne44r*w@
    depends_on:
      dbsql:
        condition: service_started
        restart: true

networks:
  db-platform-net:
    driver: bridge
