version: "3.5"

services:
  dbsql:
    image: mysql
    container_name: dbsql
    hostname: dbsql
    environment:
      - MYSQL_USER=teste
      - MYSQL_PASSWORD=teste
      - MYSQL_ROOT_PASSWORD=teste
    volumes:
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:rw

  db-sql-02:
    image: mysql
    container_name: db-sql-02
    hostname: db-sql-02
    environment:
      - MYSQL_USER=teste
      - MYSQL_PASSWORD=teste
      - MYSQL_ROOT_PASSWORD=teste
    volumes:
      - ./src/db/sqlteste.sql:/docker-entrypoint-initdb.d/sqlteste.sql:rw

  db-sql-03:
    image: mysql
    container_name: db-sql-03
    hostname: db-sql-03
    environment:
      - MYSQL_USER=teste
      - MYSQL_PASSWORD=teste
      - MYSQL_ROOT_PASSWORD=teste
    volumes:
      - ./src/db/sqlteste.sql:/docker-entrypoint-initdb.d/sqlteste.sql:rw

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste

  pg:
    image: postgres
    container_name: pg
    hostname: pg
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste

  db-maria:
    image: mariadb
    container_name: db-maria
    hostname: db-maria
    environment:
      - MARIADB_USER=teste
      - MARIADB_PASSWORD=teste
      - MARIADB_ROOT_PASSWORD=asdasdasdasdas
    volumes:
      - ./src/db/sqlteste.sql:/docker-entrypoint-initdb.d/sqlteste.sql:rw

  db-maria-02:
    image: mariadb
    container_name: db-maria-02
    hostname: db-maria-02
    environment:
      - MARIADB_USER=teste
      - MARIADB_PASSWORD=teste
      - MARIADB_ROOT_PASSWORD=asdasdasdasdas
    volumes:
      - ./src/db/sqlteste.sql:/docker-entrypoint-initdb.d/sqlteste.sql:rw

  db:
    image: mysql
    container_name: db
    hostname: db
    environment:
      - MYSQL_USER=teste
      - MYSQL_PASSWORD=teste
      - MYSQL_ROOT_PASSWORD=teste
    volumes:
      - ./src/db/sqlteste.sql:/docker-entrypoint-initdb.d/schema.sql:rw
  web:
    build: .
    restart: on-failure
    container_name: web
    hostname: web
    ports:
      - "3000:3000"
    environment:
      - DB_USER=root
      - DB_PASSWORD=teste
      - DB_ADDRESS=dbsql:3306
      - DB_NAME=db_platform
      - GLOBAL_DB_USER=teste
      - GLOBAL_USER_PWD=teste
      - NEW_USER_PWD=teste
    depends_on:
      db:
        condition: service_completed_successfully
        restart: true
      dbsql:
        condition: service_completed_successfully
        restart: true

networks:
  default:
    driver: bridge
    name: db-platform
