// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Base() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link rel=\"stylesheet\" type=\"text/css\" href=\"/public/css/styles.css\"><script src=\"/public/js/htmx.min.js\"></script><title>DB PLatform</title></head><body><nav class=\"bg-slate-300\"><ul class=\"flex justify-between items-center p-6\"><li><img src=\"/public/img/logo.png\" alt=\"logo\" class=\"max-w-36\"></li><li><a href=\"/settings/dbs\" class=\"block\">Settings</a></li></ul></nav><main><div class=\"grid grid-cols-[300px_auto] h-screen\"><div class=\"border-gray-600 border-r-2\"><ul class=\"p-5 grid gap-3\" hx-boost=\"true\"><li><a href=\"/\" class=\"block\">Home</a></li><li><a href=\"/db/create-user\" class=\"block\">Create Database User</a></li><li><a href=\"/db/delete-user\" class=\"block\">Delete Database User</a></li><li><a href=\"/user/reset-password\" class=\"block\">Reset Password</a></li><li><a href=\"/user/logout\" class=\"block\">Logout</a></li></ul></div><div class=\"grid grid-rows-[70px_auto]\"><div class=\"h-full p-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if ctx.Value("isLoggedIn").(bool) {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div>logged in t</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div><script src=\"https://unpkg.com/htmx.org/dist/ext/disable-element.js\"></script></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
