services:
  mysql:
    image: mysql
    ports:
      - 3001:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - ../src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:rw
    # command: mysql -u root -ptest && CREATE USER 'user'@'localhost' IDENTIFIED BY 'password';

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=test

  mariadb:
    image: mariadb
    ports:
      - 3002:3306
    environment:
      - MARIADB_ROOT_PASSWORD=test
